//🔹 3. Redux Store + Slice for Products
//createSlice is a helper that automatically generates: A reducer function Action creators 
//,Action types
import { createSlice } from "@reduxjs/toolkit";

const productSlice = createSlice({
    name: 'products', //This slice is called "products". It will prefix all action types (e.g. "products/setProducts").
    initialState: { //The default state when the app starts:
        items: [], //→ empty product list
        loading: false, //→ not fetching products yet
        error: null, //→ no error initially
    },
    //Defines how the state changes in response to actions. Each key here is a reducer function.
    reducers: {
        //Replace the entire product list with new data (e.g., after fetching from API).
        setProducts: (state, action) => {
            state.items = action.payload; //→ expected to be an array of products.
            //example :  dispatch(setProducts([{ id: 1, name: "Laptop" }]));

        },
        //Add a new product to the list.
        addProducts: (state, action) => {
            state.items.push(action.payload); //→ a single product object.
            //example: dispatch(addProduct({ id: 2, name: "Phone" }));
        },
        updateProducts: (state, action) => {
            const index = state.items.findIndex(p => p.id === action.payload.id);
            if (index !== -1) {
                state.items[index] = action.payload;
            }
        },
        deleteProduct: (state, action) => {
            state.items = state.items.filter(p => p.id !== action.payload)
        }
    }
})

//Extracts the action creators automatically generated by Redux Toolkit.
//Now you can call dispatch(addProduct(...)) in your components.
export const { setProducts, addProducts, updateProducts, deleteProduct } = productSlice.actions;
//You’ll pass this to configureStore({ reducer: { products: productSlice.reducer } }).
export default productSlice.reducer; 