scalar BigDecimal

type Product {
  id: ID!
  name: String!
  description: String
  price: BigDecimal!
  sku: String
}

input CreateProductInput {
  name: String!
  description: String
  price: BigDecimal!
  sku: String
}

input UpdateProductInput {
  name: String
  description: String
  price: BigDecimal
  sku: String
}

type CartItem {
  id: ID!
  product: Product!
  quantity: Int!
}

type Cart {
  id: ID!
  userId: String!
  items: [CartItem!]!
}

input AddToCartInput {
  productId: ID!
  quantity: Int = 1
}

input OrderItemInput {
  productName: String!
  quantity: Int!
  price: Float!
}

type OrderItem {
  id: ID!
  productName: String!
  quantity: Int!
  price: BigDecimal!
}

type Order {
  id: ID!
  userEmail: String!
  totalAmount: Float!
  paymentStatus: String!
  items: [OrderItem!]!
}

type Query {
  products: [Product]
  productById(id: ID!): Product
  cart(userId: String!): Cart
  hello: String
  testProducts: [TestProduct]
}

type Mutation {
  createProduct(input: CreateProductInput!): Product
  updateProduct(id: ID!, input: UpdateProductInput!): Product
  deleteProduct(id: ID!): Boolean
  addToCart(userId: String!, input: AddToCartInput!): Cart
  removeFromCart(userId: String!, productId: ID!): Cart
  createPaymentIntent(amount: Int!): PaymentIntentResponse!
  createOrder(userEmail: String!, totalAmount: Float!, items: [OrderItemInput!]!): Order
}

type PaymentIntentResponse {
  clientSecret: String!
}

type Subscription {
  productAdded: Product
  expensiveProducts: Product
}

type TestProduct {
  id: ID!
  name: String!
  price: Float!
}
