/**
Fetches all products from backend (useQuery).
Subscribes to live additions (useSubscription).
Updates Redux store with fetched data.
Allows delete & add-to-cart.
Keeps UI and backend fully synced.
 */

//useEffect lets you run side effects like fetching data after the component renders.
import React, { useEffect } from "react";

//useQuery → run a GraphQL query (get data)
//useSubscription → listen to live updates (like new product added)
//useMutation → run a GraphQL mutation (create, update, delete)
import { useQuery, useSubscription, useMutation } from "@apollo/client/react";

//useDispatch() → to send actions to Redux store (e.g., dispatch(setProducts()))
//useSelector() → to read data from the Redux store (e.g., state.products.items)
import { useDispatch, useSelector } from "react-redux";

import { useNavigate } from "react-router-dom"; // ✅ Add navigation
import { GET_PRODUCTS, PRODUCT_ADDED, DELETE_PRODUCT } from "./graphql/productQueries"; //execute GQL 

//➡ These are Redux actions auto-generated by your createSlice.
//setProducts() — load all products from backend
import { setProducts, deleteProduct, addProducts } from "./slices/ProductSlice";

//Redux action to add a selected product into cart state.
import { addItem } from "./slices/cartSlice"; // ✅ Add cart slice import

//➡ UI component responsible for rendering a single product card/item
//  (with “Add to Cart” and “Delete” buttons).
import ProductItem from "./ProductItem";

function ProductList() {
    const dispatch = useDispatch(); //dispatch → to update Redux store
    const navigate = useNavigate(); // ✅ hook for navigation
    //➡ Reads products array from Redux store.
    const products = useSelector((state) => state.products?.items || []);

    // ✅ Initial fetch - Fetching Products from backend
    //loading: true while fetching
    const { loading, error, data } = useQuery(GET_PRODUCTS);

    //➡ Listens to GraphQL subscription.
    // ✅ Subscription for live product additions
    const { data: subData } = useSubscription(PRODUCT_ADDED);

    // ✅ Delete mutation
    const [deleteProductMutation] = useMutation(DELETE_PRODUCT, {
        refetchQueries: [{ query: GET_PRODUCTS }],
    });

    // ✅ Load initial product data into Redux
    //Apollo hits your backend GraphQL endpoint (/graphql), when data arrives
    //Redux stores that list into state.products.items, which your UI displays.
    useEffect(() => {
        if (data) dispatch(setProducts(data.products));
    }, [data, dispatch]);

    // ✅ Handle new product added via subscription
    useEffect(() => {
        if (subData?.productAdded) dispatch(addProducts(subData.productAdded));
    }, [subData, dispatch]);

    // ✅ Delete a product - When you call deleteProductMutation({ variables: { id } }), it will:
    //Run the DELETE_PRODUCT mutation.
    //Then refetch products list from backend (ensures UI sync).
    const handleDelete = async (id) => {
        await deleteProductMutation({ variables: { id } });
        dispatch(deleteProduct(id)); //Then removes it locally in Redux too
    };

    // ✅ Add to cart + navigate
    //➡ Adds product to Redux cart and redirects to cart page.
    const handleAddToCart = (product) => {
        dispatch(addItem(product)); // add to cart state
        navigate("/cart"); // redirect to cart page
    };

    // ✅ Render section
    if (loading) return <p>Loading...</p>;
    if (error) return <p>Error! {error.message}</p>;

    return ( //🧾 Show product list
        <div style={{ padding: "20px" }}>
            <h2>🛍️ Product List</h2>
            <ul style={{ listStyle: "none", padding: 0 }}>
                {products.map((p) => ( //➡ Loops through products and renders each with ProductItem component.
                    <ProductItem
                        key={p.id}
                        product={{ ...p, price: Number(p.price) }}
                        onDelete={handleDelete}
                        onAddToCart={handleAddToCart} // ✅ Pass this down
                    />
                ))}
            </ul>
        </div>
    );
}

export default ProductList;
